# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
        
      - name: Use cachix for mathcomp
        run: |
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix use math-comp

      - name: Run nix-build
        run: |
          nix-build https://tinyurl.com/math-comp-nix --arg config 'pkgs: {coq = "8.9";  mathcomp = "1.9.0"; formal-crypto = {src = ./.; propagatedBuildInputs = with pkgs.coqPackages [ mathcomp-full ];};}' --argstr package formal-crypto --arg src './.'
